[tool.black]
exclude = '''
(
  /(
      \.git         # exclude a few common directories in the
    | \.direnv      # root of the repo
    | \.venv
    | venv
  )/
)
'''

[tool.ruff]
exclude = [
  "*.egg-info",
  ".direnv",
  ".git",
  ".github",
  ".venv",
  "__pycache__",
  "build",
  "dist",
  "source",
]
extend-ignore = [
  "E501",
  "E741",
]
line-length = 88
extend-select = [
  "A",  # flake8-builtins
  "I",  # isort
  "INP",  # flake8-no-pep420
  "ISC",  # flake8-implicit-str-concat
  "UP",  # pyupgrade
  "W",  # pycodestyle warning
]

[tool.ruff.isort]
lines-after-imports = 2
