[tool.black]
exclude = '''
(
  /(
      \.git         # exclude a few common directories in the
    | \.direnv      # root of the repo
    | \.venv
    | venv
  )/
)
'''

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
line_length = 88
lines_after_imports = 2
multi_line_output = 3
skip_glob = [".direnv", ".venv", "venv"]
use_parentheses = true
