---
name: Linting

on:
  push:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements.*.txt
      - uses: extractions/setup-just@69d82fb0233557aec017ef13706851d0694e0f1d  # v1.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tooling checks
        run: just check
