name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '* 1 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4

    - name: Set up uv
      uses: astral-sh/setup-uv@887a942a15af3a7626099df99e897a18d9e5ab3a  # v5.1.0
      with:
        version: "latest"

    - uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6  # v2.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Fetch latest data
      run: just scrape

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push

    - name: Build SQLite database
      run: just build

    - uses: superfly/flyctl-actions/setup-flyctl@master
    - name: Publish to Fly
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      run: just deploy
