name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '* 1 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"
        cache-dependency-path: requirements.*.txt

    - uses: extractions/setup-just@69d82fb0233557aec017ef13706851d0694e0f1d  # v1.6.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Fetch latest data
      run: just scrape

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push

    - name: Build SQLite database
      run: just build

    - name: Deploy database to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: just deploy
